CREATE TABLE IF NOT EXISTS bookings (
    id BIGSERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    tickets INTEGER NOT NULL CHECK (tickets > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
